### ISSUE TITLE
Request: Document native manifest JSON location

### ISSUE THREAD

**Issue by Frederick888** [thunderbird/developer-docs#147]
I was redirected from [1].

Due to [2], the user-local native manifest location is different from
Firefox as documented in [3][4] under macOS.

At the moment this piece of info is very obscure. I was working on an
MailExtension which leveraged native messaging and Thunderbird just kept
complaining 'No such native application xxx' no matter where I put the
manifest file.

I ended up having to download Thunderbird's source code which led me to
[2] to finally get it working.

So I reckon it'd be great if we can get this documented. I can create a
PR and copy [1] over if you can advise where to add this.

[1] https://github.com/mdn/content/pull/18086
[2] https://hg.mozilla.org/mozilla-central/file/012ceb5e65c2f22b19e921aedfe2aef311ea3631/toolkit/xre/nsXREDirProvider.cpp#l1347
[3] https://wiki.mozilla.org/WebExtensions/Native_Messaging
[4] https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#manifest_location

**Comment by tech189** [comment]
I made a PR for this, let me know if the wording could be any clearer or if anything is missing!

**Comment by Frederick888** [comment]
@tech189 I wasn't able to confirm whether `/Library/Mozilla/NativeMessagingHosts/` was the global path for TB macOS, so I'd appreciate it if you can check. But since I doubt many people actually need global TB messaging hosts, even without that piece of info, I think the PR is :100:! Thank you.

**Comment by tech189** [comment]
I just checked, for the global path it looks like it works in `/Library/Application Support/Mozilla/NativeMessagingHosts/` but not in `/Library/Mozilla/NativeMessagingHosts/`! I'll clarify in the PR that the global path is the same as written in MDN docs.

**Comment by Frederick888** [comment]
@tech189 I'm sure it'll save some poor sysadmin tons of time down the line :P
