### ISSUE TITLE
Explain why/if loading of customElements.js no longer necessary?

### ISSUE THREAD

**Issue by eyalroz** [thunderbird/developer-docs#160]
As part of the work on my extension (removedupes) to make it compatible with TB 68, I began loading [`customElements.js`](https://searchfox.org/comm-central/source/mail/base/content/customElements.js) in a dialog my extension uses.

At some point between v68.0 and TB version 102, however, this seems to have become redundant, as - somehow - that script gets loaded for me; or at least, some of the scripts it proceeds to load get loaded for me. 

I don't remember why I had started loading this in the first place, but assuming it wasn't just some invalid scribble on my part - perhaps the documents here need to mention when one should stop loading that script.

See also [BMO bug 1590469](https://bugzilla.mozilla.org/show_bug.cgi?id=1590469)

**Comment by jobisoft** [comment]
I do not know, but I do not think the answer is needed any more.
