### ISSUE TITLE
"Adapt to TB 115" page explains 3-pane window restructuring poorly

### ISSUE THREAD

**Issue by eyalroz** [thunderbird/developer-docs#165]
The section on "Rework of Thunderbird's main messenger window" in the "Adapt to Changes in Thunderbird 103-115" page does not explain the changes and their implications well enough:

1. It does not remind the reader about the structure of the 3-pane window.
2. It does not explain in what contexts the phrase `mail3PaneWindow` was used, which would now see the use of `about:3pane`
3. It does not explain the relation between window/window-object (?) renaming and the switch to a single browser element 
4. It does not discuss whether document elements are the same as before or not
5. It does not link to a reminder of what a browser element is
6. It has no rough diagram of "before" and "after" structural relations between parts/elements of the main messenger window
7. It does not explain how the restructuring affects actions such as: 
   * `document.getElementById()` (what will now fail)
   * Use of `window.top`, `window.parent` etc.
8. It does not suggest concrete changes to overlays of `messenger.xhtml`
9. It does not explain what code one might have used previously, which the four suggested options are a replacement of.

**Comment by jobisoft** [comment]
We tried to be a bit more verbose.
