### ISSUE TITLE
"Adapt to TB 115" page needs to mention -moz-image-region going away

### ISSUE THREAD

**Issue by eyalroz** [thunderbird/developer-docs#167]
Many groups TB buttons used to use a single image, with a `-moz-image-region` custom property to choose which rectangle within the image to use for the button. However - in TB 115, that property is no longer recognized for buttons (or at all?) - and no TB-bundled extensions (messenger, composer, calendar etc.) use it any more.

That should be discussed on the page, and an appropriate alternative offered.

(TBH, I don't know what that alternative should be. Does `-moz-image-rect` work?)

**Comment by jobisoft** [comment]
The proposed alternative is not use it any more. See

https://searchfox.org/mozilla-esr102/rev/2ac4b481997e2bcf569c91d8bb7ab1e5a0b7b1b0/browser/tools/mozscreenshots/mozscreenshots/extension/configurations/Buttons.jsm#99-104

vs

https://searchfox.org/mozilla-esr115/rev/2090e4f3ef018a54be7f60c5832fe8691e8d5a20/browser/tools/mozscreenshots/mozscreenshots/extension/configurations/Buttons.sys.mjs#90-95

Will add that info.
