### ISSUE TITLE
broken links: writing mochitest tests

### ISSUE THREAD

**Issue by zhus-on-first** [thunderbird/developer-docs#176]
On https://developer.thunderbird.net/thunderbird-development/testing/writing-mochitest-tests, there are two broken links:

- [BrowserTestUtils](https://searchfox.org/mozilla-central/source/testing/mochitest/BrowserTestUtils/BrowserTestUtils.jsm) 
- [MailTestUtils](https://searchfox.org/comm-central/source/mailnews/test/resources/MailTestUtils.jsm)

Some general searching on searchfox.org didn't turn up appropriate updated links, but I did find a doc for BrowserTestUtils here: https://firefox-source-docs.mozilla.org/testing/browser-chrome/browsertestutils.html

**Comment by hellsworth** [comment]
@zhus-on-first thank you so much for finding and reporting these broken links! There has been some effort to migrate some .jsm files to .sys.mjs files so I've updated these two searchfox.org links.
