### ISSUE TITLE
ics import error

### ISSUE THREAD

**Issue by Maik1307** [thunderbird/developer-docs#184]
Hi,

I get the following error when I try to import some ics dates to thunderbird kalender (in Mint)

`Calendar: CalDAV: Unexpected status adding item to Arbeit: 403
BEGIN:VCALENDAR

PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN

VERSION:2.0

BEGIN:VTIMEZONE

TZID:W. Europe Standard Time

BEGIN:DAYLIGHT

DTSTART:20211031T030000

TZOFFSETFROM:+0100

TZOFFSETTO:+0200

RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU;BYHOUR=2;BYMINUTE=0;BYSECOND=0

TZNAME:Central European Time

END:DAYLIGHT

BEGIN:STANDARD

DTSTART:20220327T020000

TZOFFSETFROM:+0200

TZOFFSETTO:+0100

RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU;BYHOUR=3;BYMINUTE=0;BYSECOND=0

TZNAME:Central European Time

END:STANDARD

END:VTIMEZONE

BEGIN:VEVENT

CREATED:20240529T133246Z

DTSTAMP:20240529T142839Z

UID:5.9411676470.9411717665.0@cytric.net

SUMMARY:Zug von Stollberg (Sachs) nach Bochum

PRIORITY:0

STATUS:BOOKED

CATEGORIES:Bahnbuchung

DTSTART;TZID=W. Europe Standard Time:20240610T052100

DTEND;TZID=W. Europe Standard Time:20240610T132300

CLASS:PUBLIC

DESCRIPTION:Von Stollberg (Sachs) Nach Bochum Hbf (De)\nAngefragt für: Mai

 k  Haenig\n\nBuchungscode: 135117523\n\nMontag\, 10 Juni 2024\nDeutsche Bah

 n - CB 55672 Zweite Klasse\nAbreise von Stollberg (Sachs) um 05:21\nAnkunft

  in Glauchau (Sachs) (De) um 05:57\nMontag\, 10 Juni 2024\nDeutsche Bahn - 

 RE  3654 Zweite Klasse\nAbreise von Glauchau (Sachs) (De) um 06:07\nAnkunft

  in Göttingen (De) um 09:51\nMontag\, 10 Juni 2024\nDeutsche Bahn - ICE 11

 72 Zweite Klasse\nAbreise von Göttingen (De) um 10:16\nAnkunft in Hannover

  Hbf (De) um 10:56\nMontag\, 10 Juni 2024\nDeutsche Bahn - ICE  942 Zweite 

 Klasse\nAbreise von Hannover Hbf (De) um 11:31\nAnkunft in Bochum Hbf (De) 

 um 13:23\n\nBestätigungsnummer bei Deutsche Bahn (NVS): 135117523\nGebucht

  von: Maik  Haenig\n

LOCATION:Stollberg (Sachs)

TRANSP:OPAQUE

END:VEVENT

END:VCALENDAR

CalDavCalendar.jsm:635
NS_ERROR_FAILURE: Server Replied with 403
    adoptItem resource:///components/calCachedCalendar.js:652
    adoptItemCallback resource:///components/calCachedCalendar.js:729
    onOperationComplete resource:///modules/CalDavCalendar.jsm:559
    notifyPureOperationComplete resource:///modules/calendar/utils/calProviderUtils.jsm:590
    notifyListener resource:///modules/CalDavCalendar.jsm:577
    doAdoptItem resource:///modules/CalDavCalendar.jsm:654
    handle resource:///modules/MessengerContentHandler.jsm:564
import-export.js:184:17
`

**Comment by hellsworth** [comment]
Hi there, thank you for taking time to report your issue however this repo is specifically for issues regarding the developer documentation found at developer.thunderbird.net.

Since you are using Mint, and I know they package and maintain their own Thunderbird deb package, I suggest reporting your issue upstream to them: forums.linuxmint.com
