### ISSUE TITLE
The TB 53-60 changes description should be more easily accessible

### ISSUE THREAD

**Issue by eyalroz** [thunderbird/developer-docs#54]
On this part of the site:

https://developer.thunderbird.net/add-ons/about-add-ons

we should, IMHO, have not just a section with the information about changes in versions 61-68, but also a similar section with the information regarding changes in versions 53-60, which currently appears here:

https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57

**Comment by jobisoft** [comment]
The group of developers benefitting from such information (now) will be tiny, and the time spend on creating this documentation is better spent on other items. Pull requests are of course appreciated.
